name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests on Node 18
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Set Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: "22"
          registry-url: https://npm.pkg.github.com
          cache-dependency-path: package-lock.json
        env:
          RUNNER_TEMP: "/tmp/"

      - name: Install Node Modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Tests
        run: npm test
